apiVersion:  apps/v1
kind: Deployment
metadata:
  name: ffdl-lcm
  namespace: {{.Values.namespace}}
  labels:
    service: ffdl-lcm
    environment: {{.Values.env}}
spec:
  selector:
    matchLabels:
      service: ffdl-lcm
      environment: {{.Values.env}}
  replicas: {{.Values.lcm.replicas}}
  template:
    metadata:
      labels:
        service: ffdl-lcm
        environment: {{.Values.env}}
        version:  {{.Values.lcm.version}}
    spec:
      volumes:
{{ if and (eq .Values.env "dev") .Values.learner.kubeSecret }}
        - name: learner-kube
          secret:
            secretName: {{.Values.learner.kubeSecret}}
{{ end }}
        - name: learner-config-volume
          configMap:
            name: learner-config
#{{ if (eq .Values.has_static_volumes true) }}
#        - name: static-volumes-config-volume
#          configMap:
#            name: static-volumes
#        - name: static-volumes-config-volume-v2
#          configMap:
#            name: static-volumes-v2
#{{ end }}
#        - name: etcd-ssl-cert
#          secret:
#            secretName: lcm-secrets
#            items: [{
#              key: DLAAS_ETCD_CERT,
#              path: etcd/etcd.cert
#            }]
######### 1.3.0  ###############
        - name: di-config
          configMap:
            name: di-config
################################
######### 1.4.0 ################
        - name: ffdl-certs
          configMap:
            name: ffdl-certs
        - name: timezone-volume
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: File
################################
######### 1.5.2 ################
        #- name: kube-config
          #hostPath:
            #path: /root/.kube
        #- name: helm-config
          #hostPath:
            #path: /root/.helm
        #- name: nfs-chart-volume
          #nfs:
            #server: 10.107.105.207
            #path: /data/nfs/charts
################################

      serviceAccount: {{.Values.docker.image_prefix}}lcm
      serviceAccountName: {{.Values.docker.image_prefix}}lcm
      containers:
      - name: ffdl-lcm-container
#        image: {{.Values.docker.registry}}/{{.Values.docker.namespace}}/{{.Values.docker.image_prefix}}lcm:{{.Values.lcm.version}}
        image: {{.Values.docker.registry}}/{{.Values.docker.namespace}}{{.Values.docker.image_prefix}}:{{.Values.lcm.version}}
{{ if .Values.docker.pullPolicy }}
        imagePullPolicy: {{.Values.docker.pullPolicy}}
{{ end }}
        ports:
        - containerPort: 8443
        volumeMounts:
{{ if and (eq .Values.env "dev") .Values.learner.kubeSecret }}
        - mountPath: /var/run/secrets/learner-kube
          name: learner-kube
{{ end }}
        - mountPath: /etc/learner-config
          name: learner-config-volume
#{{ if (eq .Values.has_static_volumes true) }}
#        - mountPath: /etc/static-volumes
#          name: static-volumes-config-volume
#        - mountPath: /etc/static-volumes-v2
#          name: static-volumes-config-volume-v2
#{{ end }}
#        - mountPath: /etc/certs/
#          name: etcd-ssl-cert
#          readOnly: true
####### 1.3.0 ############
        - mountPath: /etc/mlss/
          name: di-config
##########################
####### 1.4.0 ############
        - mountPath: /etc/ssl/dlaas/
          name: ffdl-certs
        - name: timezone-volume
          mountPath: /etc/localtime
##########################
######### 1.5.2 ################
        #- name: kube-config
          #mountPath: /config/.kube/
        #- name: helm-config
          #mountpath: /config/.helm/
        #- name: nfs-chart-volume
          #mountPath: /tmp/charts
##########################
        env:
        - name: DLAAS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DLAAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_LEARNER_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_SHARED_VOLUME_STORAGE_CLASS
          value: {{.Values.lcm.shared_volume_storage_class}}
        - name: DLAAS_LOAD_TRAINING_DATA_MEM_IN_MB
          value: "{{.Values.lcm.load_training_data_mem_in_mb}}"
        - name: DLAAS_MILLI_CPU
          value: "{{.Values.lcm.milli_cpu}}"
        - name: DLAAS_MEM_IN_MB
          value: "{{.Values.lcm.mem_in_mb}}"
        - name: DLAAS_DEVICE_PLUGIN
          value: "{{.Values.lcm.device_plugin}}"
        - name: DLAAS_IMAGE_TAG
          value: {{.Values.restapi.version}}
        - name: DLAAS_IMAGE_PULL_POLICY
          value: {{.Values.docker.pullPolicy}}
        - name: DLAAS_ENV
          value: {{.Values.env}}
        - name: DLAAS_LOGLEVEL
          value: {{.Values.log.level}}
        #- name: DLAAS_MLSSGID
          #value: {{.Values.lcm.mlssGroupId}}
        - name: DLAAS_IMAGE_PREFIX
          value: {{.Values.docker.image_prefix}}
        - name: DLAAS_LEARNER_TAG
          value: {{.Values.learner.tag}}
        - name: DLAAS_LEARNER_REGISTRY
          value: {{.Values.docker.registry}}/{{.Values.learner.docker_namespace}}
        - name: LINKIS_ADDRESS
          value: {{.Values.linkis.address}}
        - name: LINKIS_TOKEN_CODE
          value: {{.Values.linkis.tokenCode}}
        - name: ENVIR
          value: {{.Values.envir}}
        - name: FLUENT_BIT_LOG_PATH
          value: {{.Values.lcm.fluent_bit_log_path}}
        - name: DLAAS_ETCD_ADDRESS
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_ETCD_ADDRESS
        - name: DLAAS_ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_ETCD_USERNAME
        - name: DLAAS_ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_ETCD_PASSWORD
        - name: DLAAS_ETCD_PREFIX
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_ETCD_PREFIX
        - name: DLAAS_PUSH_METRICS_ENABLED
#          value: "false"
          value: "true"
        - name: DLAAS_MONGO_ADDRESS
          value: mongo.$(DLAAS_POD_NAMESPACE).svc.cluster.local
        - name: DLAAS_MONGO_USERNAME
          value: {{.Values.mongo.username}}
        - name: DLAAS_MONGO_PASSWORD
          value: {{.Values.mongo.password}}
        - name: DLAAS_OBJECTSTORE_TYPE
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_OBJECTSTORE_TYPE
        - name: DLAAS_OBJECTSTORE_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_OBJECTSTORE_AUTH_URL
        - name: DLAAS_OBJECTSTORE_USER_NAME
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_OBJECTSTORE_USER_NAME
        - name: DLAAS_OBJECTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_OBJECTSTORE_PASSWORD
##########
##1.5.1###
        - name: FLUENT_ELASTICSEARCH_HOST
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: FLUENT_ELASTICSEARCH_HOST
        - name: FLUENT_ELASTICSEARCH_PORT
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: FLUENT_ELASTICSEARCH_PORT
        - name: FLUENT_ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: FLUENT_ELASTICSEARCH_USER
        - name: FLUENT_ELASTICSEARCH_PASSWD
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: FLUENT_ELASTICSEARCH_PASSWD
##########
##1.5.1###
        - name: HOME
          value: /config
##########
        command: ["/bin/sh", "-c"]
        args: ["DLAAS_PORT=8443 /main"]
        #args: ["dlv --listen=:40000 --headless=true --api-version=2 exec /main -- --DLASS-PORT=8443"]
        resources:
          limits:
            cpu: {{.Values.lcm.cpus}}
            memory: {{.Values.lcm.memory}}
        #livenessProbe:
        #  exec:
        #    command:
        #      - /bin/sh
        #      - -c
        #      - "grpc-health-checker --port 8443 --tls"
        #  initialDelaySeconds: 15
        #  timeoutSeconds: 2
      imagePullSecrets:
#      - name: regcred
      - name: hubsecret
      nodeSelector:
       {{range $key,$val := .Values.platformNodeSelectors}}
         {{$key}}: {{$val}}
       {{end}}
